baseURL = "https://fabiogeraci.github.io/mljourney/"
title='ML Journey'
theme = "hugo-coder"

languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsUseClasses = false
enableEmoji = true

googleAnalytics = "${{secrets.GOOGLEANALYTICS_ID}}" #"G-LEPGC6QVMG"

colorScheme = "dark"
canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[params]
author = "Fabio Geraci"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Fabio Geraci's personal website"
keywords = "blog, developer, personal"
info = ['ML/CV Deep Learning Developer' , 'Edge/Cloud Deep Learning Deployment' , 'MLOps Developer Advocate']
avatarURL = "images/image.png"
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2019

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/fabiogeraci/fabiogeraci"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 3
url = "https://twitter.com/FGeraci73/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/fabiogeraci/"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 2
url = "projects/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"


